site_name: "Dynatrace Observability Lab: Release Validation"
repo_name: "GitHub"
repo_url: "https://github.com/dynatrace-perfclinics/obslab-release-validation"
nav:
  - '1. About': index.md
  - '2. Getting Started': getting-started.md
  - '3. Validate Telemetry': validate-telemetry.md
  - '4. Create SRG': create-srg.md
  - '5. Automate SRG': automate-srg.md
  - '6. Enable Automatic Baselines': enable-auto-baselines.md
  - '7. Run a Production SRG': run-production-srg.md
  - '8. Make a Change': enable-change.md
  - '9. View Acceptance Test Results': view-acceptance-test-results.md
  - '10. Cleanup': cleanup.md
  - '11. Resources': resources.md
  - "12. What's Next?": whats-next.md
theme:
  name: material
  custom_dir: custom_theme
  palette:

  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default 
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
markdown_extensions:
  - attr_list 
  - toc:
      permalink: '#'
plugins:
    - search
    - markdownextradata
extra:
  dt:
    rumagent:
      snippet: <script type="text/javascript" src="https://js-cdn.dynatrace.com/jstag/145e12d594f/bf64904yne/c6090fd9538c45f8_complete.js" crossorigin="anonymous"></script>
  obslab: obslab-release-validation
  progressbar:
    2. Getting Started:
      - Create API Token
    3. Validate Telemetry:
      - Wait For Demo to Start
      - Access Demo User Interface
      - Validate Services
      - Validate Traces
      - Validate Metrics
      - Validate Logs
    4. Create SRG:
      - Create Site Reliability Guardian
    5. Automate SRG:
      - Create Workflow
    6. Enable Automatic Baselines:
      - Trigger the First Load Test
      - Trigger the Second Load Test
      - Trigger the Third Load Test
      - Trigger the Fourth Load Test
      - Trigger the Final Load Test
      - Wait for Completion
      - View Completed Training Runs
      - View SRG Status using DQL
      - View SRG Status
    7. Run a Production SRG:
      - Run Evaluation
    8. Make a Change:
      - Update Feature Flag
      - Run Acceptance Load Test
      - View Configuration Change Events
    9. View Acceptance Test Results:
      - View Data
      - Analyse Failed Request
      - Roll Back Change
    
extra_css: # relative to docs/
  - css/style.css
extra_javascript: # relative to docs/
  - js/script.js